// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs0CoGhBh_ZPs37F-v0VITNVIwQllfU5g',
    appId: '1:879059242373:web:73d635be117ee4902108ec',
    messagingSenderId: '879059242373',
    projectId: 'atividade-30-05',
    authDomain: 'atividade-30-05.firebaseapp.com',
    storageBucket: 'atividade-30-05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2sVkK4eLygV0U1bNSrBg4heuh35dZHrw',
    appId: '1:879059242373:android:2c5981fd007d4d112108ec',
    messagingSenderId: '879059242373',
    projectId: 'atividade-30-05',
    storageBucket: 'atividade-30-05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJhiNJW0izc0NO_fBXs3ULXwFY87RTdlg',
    appId: '1:879059242373:ios:aef8c12a3bc31c092108ec',
    messagingSenderId: '879059242373',
    projectId: 'atividade-30-05',
    storageBucket: 'atividade-30-05.appspot.com',
    iosClientId: '879059242373-v4rsqgutcvigbgu2p4ik8et09k8e2cep.apps.googleusercontent.com',
    iosBundleId: 'com.example.atividade3005',
  );
}
